var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc('','');
subject.inc(010,'');
subject.inc(010,"");
subject.inc(010,undefined);
subject.inc(-1,undefined);
subject.inc(-1,"");
subject.weird('','','','');
subject.weird('','',4210,'');
subject.weird('',010,4210,'');
subject.weird('',010,41,'');
subject.weird('',-1,41,'');
subject.weird('',-1,41,"werw");
subject.weird('',-1,41,"strict");
subject.weird('',010,41,"strict");
subject.weird('',010,41,"");
subject.weird(8,010,41,"");
subject.weird(-3,010,41,"");
subject.weird(-3,010,41,"werw");
subject.weird(-3,010,41,"strict");
subject.weird(-3,010,4210,"werw");
subject.weird(-3,010,4210,"strict");
subject.weird(8,010,4210,"strict");
subject.weird(8,-1,4210,"strict");
subject.weird(8,-1,41,"strict");
subject.weird(8,-1,41,"");
subject.weird(8,010,41,"werw");
subject.weird(8,010,4210,"werw");
subject.weird(8,010,4210,"");
subject.weird(8,-1,4210,"");
subject.weird(8,-1,4210,"werw");
subject.weird(-3,-1,4210,"werw");
subject.weird(-3,-1,41,"");
subject.weird(-3,010,4210,"");
subject.weird(-3,-1,4210,"");
subject.weird(-3,-1,4210,"strict");
subject.weird(-3,-1,41,"strict");
mock({"path/fileExists":{"file1":"some file1 stuff here","file2":"some file2 stuff here"},"pathContent":{"file1":"text content"}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"file1":"some file1 stuff here","file2":"some file2 stuff here"},"pathContent":{"file1":""}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"file1":"some file1 stuff here","file2":"some file2 stuff here"},"pathContent":{"file1":""}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"file1":"some file1 stuff here","file2":"some file2 stuff here"},"pathContent":{"file1":"text content"}});
	subject.fileTest('','path/nonexistentFile');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('','path/nonexistentFile');
mock.restore();
mock({"path/fileExists":{"file1":"some file1 stuff here","file2":"some file2 stuff here"},"pathContent":{"file1":""}});
	subject.fileTest('','path/nonexistentFile');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('','path/nonexistentFile');
mock.restore();
mock({"path/fileExists":{"file1":"some file1 stuff here","file2":"some file2 stuff here"},"pathContent":{"file1":"text content"}});
	subject.fileTest('','path/nonexistentFile');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('','path/nonexistentFile');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('','path/nonexistentFile');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('','path/nonexistentFile');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('','path/nonexistentFile');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('','path/nonexistentFile');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('','path/nonexistentFile');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('','path/nonexistentFile');
mock.restore();
mock({"path/fileExists":{"file1":"some file1 stuff here","file2":"some file2 stuff here"},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"file1":"some file1 stuff here","file2":"some file2 stuff here"},"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"file1":"some file1 stuff here","file2":"some file2 stuff here"},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','path/nonexistentFile');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','path/nonexistentFile');
mock.restore();
mock({"path/fileExists":{"file1":"some file1 stuff here","file2":"some file2 stuff here"},"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','path/nonexistentFile');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','path/nonexistentFile');
mock.restore();
mock({"path/fileExists":{"file1":"some file1 stuff here","file2":"some file2 stuff here"},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','path/nonexistentFile');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','path/nonexistentFile');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','path/nonexistentFile');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','path/nonexistentFile');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','path/nonexistentFile');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','path/nonexistentFile');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','path/nonexistentFile');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','path/nonexistentFile');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/nonexistentFile','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/nonexistentFile','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"file1":"some file1 stuff here","file2":"some file2 stuff here"},"pathContent":{"file1":""}});
	subject.fileTest('path/nonexistentFile','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/nonexistentFile','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"file1":"some file1 stuff here","file2":"some file2 stuff here"},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/nonexistentFile','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/nonexistentFile','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('path/nonexistentFile','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/nonexistentFile','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/nonexistentFile','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/nonexistentFile','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('path/nonexistentFile','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/nonexistentFile','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"file1":"some file1 stuff here","file2":"some file2 stuff here"},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/nonexistentFile','path/nonexistentFile');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/nonexistentFile','path/nonexistentFile');
mock.restore();
mock({"path/fileExists":{"file1":"some file1 stuff here","file2":"some file2 stuff here"},"pathContent":{"file1":""}});
	subject.fileTest('path/nonexistentFile','path/nonexistentFile');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/nonexistentFile','path/nonexistentFile');
mock.restore();
mock({"path/fileExists":{"file1":"some file1 stuff here","file2":"some file2 stuff here"},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/nonexistentFile','path/nonexistentFile');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/nonexistentFile','path/nonexistentFile');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('path/nonexistentFile','path/nonexistentFile');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/nonexistentFile','path/nonexistentFile');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/nonexistentFile','path/nonexistentFile');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/nonexistentFile','path/nonexistentFile');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('path/nonexistentFile','path/nonexistentFile');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/nonexistentFile','path/nonexistentFile');
mock.restore();
subject.normalize('');
subject.format('','','');
subject.blackListNumber('');
subject.blackListNumber('212-928-4304');
subject.blackListNumber('263-307-0632');
