#!/bin/bash
GIT_WORK_TREE=$ROOT/green-www/ git checkout -f
cd $ROOT/green-www; 
docker stop green_app
docker rm green_app
docker rmi localhost:5000/simple_app:current_green
docker pull localhost:5000/simple_app:green
docker tag localhost:5000/simple_app:green localhost:5000/simple_app:current_green
docker run -p 9001:8080 -d --name green_app localhost:5000/simple_app:current_green
